name: GitHub Pages
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
        with:
          enablement: true     # <-- penting: aktifkan Pages otomatis
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "."
      - id: deploy
        uses: actions/deploy-pages@v4
